### ISSUE TITLE
Rename repo to "ci-runners"

### ISSUE THREAD

**Issue by wipfli** [maplibre/ci-runners#3]
Thanks for taking the initiative to automate our self-hosted runners. Please rename this repository to "ci-runners" or similar. For branding purposes, we want to keep the term "maplibre" directly associated with the rendering libraries for JS, iOS, and Android. Other projects in the MapLibre GitHub organization should not use the term "maplibre" in their name.

**Comment by louwers** [comment]
:heavy_check_mark:
